### PR TITLE
v2o.5.5 CHS Translation with Patchouli

### PR DESCRIPTION
**Pull request by WuzgXY-GitHub**
pls squash

### CODE REVIEW

**Comment by WuzgXY-GitHub** [comment]
The CHS localisation might be changed again and again in the near future, because we many translators have started playing the mod in survival so we will check every entry, but you can merge this first 😛

**Comment by WuzgXY-GitHub** [comment]
Can I put translations of all the script addons I have translated into zh_cn.lang of NuclearCraft as shown in the file? It would be much easier for me and every script addon maker to manager localisations. I will add descriptions to prevent unpredicted actions of changing localisations wrongly by other translators

**Comment by WuzgXY-GitHub** [comment]
The NCOUTO part was made by @TheRealKamisama, and shared under CC BY-NC-SA 4.0 to here. I made a few tweaks to it also

**Comment by tomdodd4598** [comment]
> Can I put translations of all the script addons I have translated into zh_cn.lang of NuclearCraft as shown in the file? It would be much easier for me and every script addon maker to manager localisations. I will add descriptions to prevent unpredicted actions of changing localisations wrongly by other translators

I'm sure it's fine, thanks to the both of you :)

**Pull request merged**
