### PR TITLE
Fix that annoying ic2 enet spam

### PR DESCRIPTION
**Pull request by fscan**
Didn't do a lot of testing.

### CODE REVIEW

**Comment by fscan** [comment]
BTW, it would be helpful to have the most recent source code here on github. Current master does not compile (CraftTweaker api stuff).

**Comment by turbodiesel4598** [comment]
Fantastic - thanks very much for sorting this out, as I was not exactly sure what to do myself :P
Will get the source updated soon - now back from uni to go through these pull requests and bug reports :)

**Comment by turbodiesel4598** [comment]
Ack... you know, I had a slight feeling there would be an issue with this - the thing that was actually causing the spam was my attempt to keep IC2 cables connected after block updates. By removing the code causing the spamming, IC2 cables now, once again, disconnect as soon as the machine starts or stops.

So in other words, this is still an open issue...

**Comment by fscan** [comment]
Hmm. That would mean that something is calling `invalidate`. And if that something is not MC/Forge immediately before TE removal this is just wrong.

**Comment by fscan** [comment]
Well ok, i had another look and yeah .. the problem is that you have different *blocks* for the active and idle state. This complicates things a lot as your block gets replaced on every state change. Your "fix" is calling setBlock with the same instance, which calls invalidate  and removes the ic2 connection. This could severely affect performance of larger energy/duct networks.
The proper solution would probably be to just make active/idle blockstates of the same block.

**Pull request merged**
