### PR TITLE
Use the passed-in state instead of calling getBlockState

### PR DESCRIPTION
**Pull request by josephcsible**
Fixes Aang23/UndergroundBiomesConstructs#3 and probably some other bugs I don't know about. Is also a tiny performance win.

### CODE REVIEW

**Comment by turbodiesel4598** [comment]
Thanks!

**Comment by NickelHub** [comment]
Would you mind pushing a new build to curse then?

**Comment by Aang23** [comment]
I did provide a workaround in UBC too.

**Comment by turbodiesel4598** [comment]
New build out tonight ;)

**Comment by Aang23** [comment]
Perfect ! Thanks.
I think the I'll let the fix in for something like 2 weeks in case some peoples takes time to update.

**Comment by NickelHub** [comment]
> New build out tonight ;)

Great. :D

**Comment by turbodiesel4598** [comment]
Awesome!

**Pull request merged**
