### PR TITLE
Simplified Chinese Translation

### PR DESCRIPTION
**Pull request by WuzgXY-GitHub**
Double-checked and corrected almost every wrong translation, also including those abbreviations.

I didn't translate the cfg guides, and I hope that won't cause problems. I may tranlsate them only if I've got enough time for understanding what they mean exactly to make sure there wouldn't be ambiguities. Sorry for that :)
Also, I didn't translate some of the advancements and TiC modifiers which are too difficult to not only translate them into Chinese but also keep their original meanings. For those ones and the ones which might have better translations, I've added comments as "pun or meme" for recognizing and re-translating.

Btw, don't mind the number of deletions and additions, they are not true. They just inherited the translation of pre-overhaul version.

### CODE REVIEW

**Comment by WuzgXY-GitHub** [comment]
And don't mind the number of deletions and additions, they are not true. They just inherited the translation of pre-overhaul version.

**Comment by WuzgXY-GitHub** [comment]
I'm not sure about the translation of Line 3167 in the English file because it seems like that there shouldn't even be space between blades and stators, but I've translated it into what it might be.

> The space between the sets of rotor blades and stators must be empty for the turbine to form.

**Comment by IBeiKui** [comment]
_干的不错我的老伙计。_

**Comment by turbodiesel4598** [comment]
Thanks very much :)

**Pull request merged**
