### PR TITLE
Custom trigger (Advancements) for Multiblock forming events

### PR DESCRIPTION
**Pull request by igentuman**
This gives a posibillity to give an advancements for building multiblocks.

Just in a right place and time call methods:
MultiblockTrigger.FISSION_REACTOR_FORMED.trigger((EntityPlayerMP)player);
MultiblockTrigger.MOLTENSALT_REACTOR_FORMED.trigger((EntityPlayerMP)player);
MultiblockTrigger.HEATEXCHANGER_FORMED.trigger((EntityPlayerMP)player);
MultiblockTrigger.TURBINE_FORMED.trigger((EntityPlayerMP)player);
This also can be used by addons. like QMD

### CODE REVIEW

**Comment by igentuman** [comment]
First of all i wanted such advancements on my server. So i can customize quests for these events. Because as for now i can only track players inventory and count quests as player received some amount of certain blocks, but this is not enough to say "player actually built a structure with this blocks"
I think this will be actually useful for other mod-packers

**Comment by turbodiesel4598** [comment]
Thanks very much for showing me how this is done! Would you be okay with me modifying this to allow for any new multiblocks (from addons such as QMD) to be added, and so that these advancements simply replace the controller crafting ones instead?

**Comment by igentuman** [comment]
> Thanks very much for showing me how this is done! Would you be okay with me modifying this to allow for any new multiblocks (from addons such as QMD) to be added, and so that these advancements simply replace the controller crafting ones instead?

Sure. You the owner.

**Comment by turbodiesel4598** [comment]
Finally time to fold this in :)

**Pull request merged**
