### PR TITLE
Fix crash on Chinese patchouli book and finish translation of current book

### PR DESCRIPTION
**Pull request by ghostbird03**
* Fixed crash when try to read Patchouli Guide book in Chinese
* Fix a tiny mistake in Patchouli Guide book/entrys/alloy (en_us)

* Tweaked some translation for more suitable for Chinese Language
+ Finished translation work of current content of Patchouli Guide book

### CODE REVIEW

**Comment by WuzgXY-GitHub** [comment]
I'm reviewing, so please don't merge yet :)

**Comment by WuzgXY-GitHub** [comment]
Pulled

**Comment by ghostbird03** [comment]
> The amount of the problems is too large so I'm just going to pull and let you see if it should be merged.

Just some text format mistakes.xd

**Comment by turbodiesel4598** [comment]
Thanks so much both of you!

**Pull request merged**
