### PR TITLE
Repair CraftTweaker integration

### LINKED ISSUE #159: [1.12.2] Cannot Remove Manufactory Recipes
Well I wanted to remove the Silicon recipe that Manufactory has, but it doesn't work and gives me: No such member:nuclearcraft

### PR DESCRIPTION
**Pull request by TheGuyRunningSouth**
Fixes #159 , #183 . Not quite sure when they added the @ZenRegister thing, but it's apparently required now.

### CODE REVIEW

**Comment by turbodiesel4598** [comment]
Thanks a bundle :)

**Comment by TheGuyRunningSouth** [comment]
You're quite welcome. Love the mod btw.

**Comment by turbodiesel4598** [comment]
Just came across a rather bizarre bug in the [latest release for 1.12.2](https://minecraft.curseforge.com/projects/nuclearcraft-mod/files/2507993).

I added a single fission recipe in the CT script. Although this did add that recipe, it also removed _every_ single default recipe!

I then tested to see if this happened with the Manufactory recipes, and it didn't... so there is obviously something weird going on with the Fission Reactor's CT support.

**Comment by turbodiesel4598** [comment]
Don't worry, that is now sorted - thanks again for the fix!

**Pull request merged**
